/* config/config.h.  Generated by configure.  */
/* config/config.h.in.  Generated from configure.ac by autoheader.  */

#ifndef __astro_io_gzstream_config_h
#define __astro_io_gzstream_config_h

//
// Load the apropriate configuration, depending on the compiler
//

#if (__GNUC__ < 3)
	#include "config/config.gcc2.h"
#else
	#include "config/config.gcc3.h"
#endif

#endif
