//
//     !DO NOT EDIT! - file generated by mkuseall.pl - !DO NOT EDIT!
//
//   useall.h header - makes all included libpeyton namespace functions
//	available in global namespace (through using keyword)
//

#ifdef __peyton_io_magick
	using namespace __peyton_io_magick;
	#undef __peyton_io_magick
#endif

#ifdef __peyton_io_compress
	using namespace __peyton_io_compress;
	#undef __peyton_io_compress
#endif

#ifdef __peyton_io_fits
	using namespace __peyton_io_fits;
	#undef __peyton_io_fits
#endif

#ifdef __peyton_io
	using namespace __peyton_io;
	#undef __peyton_io
#endif

#ifdef __peyton_net
	using namespace __peyton_net;
	#undef __peyton_net
#endif

#ifdef __peyton_math
	using namespace __peyton_math;
	#undef __peyton_math
#endif

#ifdef __peyton_math_numeric_integrators
	using namespace __peyton_math_numeric_integrators;
	#undef __peyton_math_numeric_integrators
#endif

#ifdef __peyton_sdss
	using namespace __peyton_sdss;
	#undef __peyton_sdss
#endif

#ifdef __peyton_util
	using namespace __peyton_util;
	#undef __peyton_util
#endif

#ifdef __peyton_constants
	using namespace __peyton_constants;
	#undef __peyton_constants
#endif

#ifdef __peyton_image
	using namespace __peyton_image;
	#undef __peyton_image
#endif

#ifdef __peyton__image
	using namespace __peyton__image;
	#undef __peyton__image
#endif

#ifdef __peyton_coordinates
	using namespace __peyton_coordinates;
	#undef __peyton_coordinates
#endif

#ifdef __peyton_math
	using namespace __peyton_math;
	#undef __peyton_math
#endif

#ifdef __peyton_asteroids
	using namespace __peyton_asteroids;
	#undef __peyton_asteroids
#endif

#ifdef __peyton
	using namespace __peyton;
	#undef __peyton
#endif

#ifdef __peyton_exceptions
	using namespace __peyton_exceptions;
	#undef __peyton_exceptions
#endif

#ifdef __peyton_system
	using namespace __peyton_system;
	#undef __peyton_system
#endif

#ifdef __peyton_time
	using namespace __peyton_time;
	#undef __peyton_time
#endif

#ifdef __peyton_system
	using namespace __peyton_system;
	#undef __peyton_system
#endif

#ifdef __peyton_util
	using namespace __peyton_util;
	#undef __peyton_util
#endif

#ifdef __peyton_exceptions
	using namespace __peyton_exceptions;
	#undef __peyton_exceptions
#endif

#ifdef __peyton_image
	using namespace __peyton_image;
	#undef __peyton_image
#endif
