/* config/config.hh.  Generated by configure.  */
/* config/config.hh.in.  Generated from configure.ac by autoheader.  */

/* whether wchar_t memory functions exists */
/* #undef GZSTREAM_HAVE_WCHAR_FUNCS */

/* whether std::char_traits<wchar_t> is defined */
#define GZSTREAM_HAVE_WCHAR_IO 1

/* Whether to support wchar_t based streams */
/* #undef GZSTREAM_HAVE_WCHAR_SUPPORT */

/* whether wchar_t is defined */
/* #undef GZSTREAM_HAVE_WCHAR_T */

/* whether std::char_traits<char> is defined */
/* #undef GZSTREAM_NEED_CHAR_TRAITS */

/* whether standard streambuf header is available */
/* #undef GZSTREAM_NEED_STREAMBUF_H */

/* Whether std::streambuf defines nested types */
/* #undef GZSTREAM_NEED_STREAMBUF_TYPES */

/* whether std::char_traits<wchar_t> is defined */
/* #undef GZSTREAM_NEED_WCHAR_TRAITS */

/* Define to 1 if you have the `fgetwc' function. */
#define HAVE_FGETWC 1

/* Define to 1 if you have the `fputwc' function. */
#define HAVE_FPUTWC 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if <wchar.h> declares mbstate_t. */
#define HAVE_MBSTATE_T 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the `ungetwc' function. */
#define HAVE_UNGETWC 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `wcslen' function. */
/* #undef HAVE_WCSLEN */

/* Define to 1 if you have the `wmemchr' function. */
/* #undef HAVE_WMEMCHR */

/* Define to 1 if you have the `wmemcmp' function. */
/* #undef HAVE_WMEMCMP */

/* Define to 1 if you have the `wmemcpy' function. */
/* #undef HAVE_WMEMCPY */

/* Define to 1 if you have the `wmemmove' function. */
/* #undef HAVE_WMEMMOVE */

/* Define to 1 if you have the `wmemset' function. */
/* #undef HAVE_WMEMSET */

/* Name of package */
#define PACKAGE "filemm"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "cholm@nbi.dk"

/* Define to the full name of this package. */
#define PACKAGE_NAME "FILE--"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "FILE-- 0.3"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "filemm"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.3"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.3"

/* Define to a type if <wchar.h> does not define. */
/* #undef mbstate_t */
