/* config/config.h.  Generated by configure.  */
/* config/config.h.in.  Generated from configure.ac by autoheader.  */

/* whether wchar_t memory functions exists */
#define GZSTREAM_HAVE_WCHAR_FUNCS 1

/* whether std::char_traits<wchar_t> is defined */
/* #undef GZSTREAM_HAVE_WCHAR_IO */

/* Whether to support wchar_t based streams */
/* #undef GZSTREAM_HAVE_WCHAR_SUPPORT */

/* whether wchar_t is defined */
/* #undef GZSTREAM_HAVE_WCHAR_T */

/* whether std::char_traits<char> is defined */
#define GZSTREAM_NEED_CHAR_TRAITS 1

/* whether standard streambuf header is available */
#define GZSTREAM_NEED_STREAMBUF_H 1

/* Whether std::streambuf defines nested types */
#define GZSTREAM_NEED_STREAMBUF_TYPES 1

/* whether std::char_traits<wchar_t> is defined */
#define GZSTREAM_NEED_WCHAR_TRAITS 1

/* Define to 1 if you have the `fgetwc' function. */
/* #undef HAVE_FGETWC */

/* Define to 1 if you have the `fputwc' function. */
/* #undef HAVE_FPUTWC */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if <wchar.h> declares mbstate_t. */
#define HAVE_MBSTATE_T 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the `ungetwc' function. */
/* #undef HAVE_UNGETWC */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `wcslen' function. */
#define HAVE_WCSLEN 1

/* Define to 1 if you have the `wmemchr' function. */
#define HAVE_WMEMCHR 1

/* Define to 1 if you have the `wmemcmp' function. */
#define HAVE_WMEMCMP 1

/* Define to 1 if you have the `wmemcpy' function. */
#define HAVE_WMEMCPY 1

/* Define to 1 if you have the `wmemmove' function. */
#define HAVE_WMEMMOVE 1

/* Define to 1 if you have the `wmemset' function. */
#define HAVE_WMEMSET 1

/* Name of package */
#define PACKAGE "gzstream"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "mjuric@astro.princeton.edu"

/* Define to the full name of this package. */
#define PACKAGE_NAME "gzstream"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "gzstream 0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "gzstream"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.1"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.1"

/* Define to a type if <wchar.h> does not define. */
/* #undef mbstate_t */
